version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries:
  - .vscode/ltex.dictionary.en-US.txt
words:
  - bugtool
  - corosync
  - Initialise
  - ltex
  - rrdd
  - xapi
  - xenserver
  - xensource
ignoreWords: []
import: []
